### ISSUE TITLE
Rust function calls.

### ISSUE THREAD

**Issue by AchalaSB** [rhysd/wain#5]
Hi,

can we use this library for Rust code If I want to call rust (FFI) function in Golang. 
Meaning I'm giving values to the arguments in runtime using golang.(reading wasm module in go) ?
Currently with memory allocation I can do this..
But finding a way without memory allocation. I thought this library may help. 

Ex: Rust code to find sum of an array. Compile code to wasm , Then read the wasm binary using go-wasmer give values to array and call the function.

Thanks

**Comment by rhysd** [comment]
Well, wain is still under development and not ready for production. I strongly recommend to use wasmer to call wasm function compiled from Rust in Go. It's far better. In addition, wasmer is far faster than wain because it utilizes JIT compilation. In addition, wain is written in Rust. It means that you need to use C-FFI with cgo to call wain API (Rust → C FFI → Go) which would introduce additional overhead and complexity.
